podTemplate(
    '''
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: 'python:2-alpine'
      command:
        - sleep
      args:
        - 99d
'''
) {

    node(POD_LABEL) {
        stage('Build python project') {
            container('python') {
                stage('Build') {
                    checkout scm
                    sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                }  
            }    
        }
    }
}
