podTemplate(yaml:
    '''
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: 'python:alpine3.15'
      command:
        - tail
      args:
        - -f /dev/null
'''
) {

    node(POD_LABEL) {
        container('python') {
            stage('Build') {
                checkout scm
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }  
        }    
    }
}
