podTemplate(yaml:
    '''
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: 'maven:3.8.5-openjdk-11'
      command:
        - sleep
      args:
        - 99d
'''
) {

    node(POD_LABEL) {
        container('python') {
            stage('Build') {
                checkout scm
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }  
        }    
    }
}
